### ISSUE TITLE
FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

### ISSUE THREAD

**Issue by 1kurops** [prometheus-community/ansible#116]
today start getting this error when running the prometmeus.prometheus role, literally yesterday it was working
Options no_log: false and true doesn't work

```
FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

Ansible version that i'm using
```
# ansible --version
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

Inventiry file
```
[prometheus]
prometheus.server.ip
```

playbook file:
```
---
- hosts: prometheus
  become: true
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_version: 2.40.7
    prometheus_web_listen_address: "0.0.0.0:9090"
    prometheus_alert_rules_files: /etc/ansible/files/*.rules
    prometheus_web_config:
      tls_server_config: {}
      http_server_config: {}
      basic_auth_users: {}
    prometheus_alertmanager_config:
      - scheme: http
        basic_auth: {}
        static_configs:
          - targets: ["127.0.0.1:9093"]
    prometheus_targets:
      node-exporter:
        - targets:
            - targert:9100
          labels:
            labels: label
    prometheus_scrape_configs:
      - job_name: "prometheus"
        metrics_path: "{{ prometheus_metrics_path }}"
        static_configs:
          - targets:
              - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
      - job_name: "node-exporter"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node-exporter.yml"
```
