### ISSUE TITLE
Target hostname not being set on scrape config

### ISSUE THREAD

**Issue by bmgante** [prometheus-community/ansible#151]
Hi,

Any idea why when installing prometheus using this ansible role it sometimes sets target with the right hostname and sometimes sets localhost as per image below (in the same instance)?

![image](https://github.com/prometheus-community/ansible/assets/27358817/801a555b-1f7a-4ad7-8592-0e7958804165)

```
prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
```
