### ISSUE TITLE
node_exporter: Basic Auth Password not properly generated

### ISSUE THREAD

**Issue by Nereis** [prometheus-community/ansible#19]
I'm using node_exporter with an authentication using this repository manually installed (see #18, commit 1e41dec)

```
- name: Setup node exporter
  import_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: 1.5.0
    node_exporter_basic_auth_users:
      prometheus: "toto"
    node_exporter_web_telemetry_path: "/node-exporter"
```

Which was working with by the past but now replaces the hashed password by *0

```
TASK [prometheus.prometheus.node_exporter : Copy the node_exporter config file] ****************************************************************************************************************************************************************************************************
--- before: /etc/node_exporter/config.yaml
+++ after: /home/nereis/.ansible/tmp/ansible-local-15437bdzf6l09/tmpz9j85ndj/config.yaml.j2
@@ -5,4 +5,4 @@
 
 
 basic_auth_users:
-  prometheus: $2b...
+  prometheus: *0
```
```
 cat /etc/node_exporter/config.yaml
---
#
# Ansible managed
#


basic_auth_users:
  prometheus: *0
```

node-exporter v1.5.0
ansible 2.10.8
python 3.10.6

Thanks!
