### ISSUE TITLE
node_exporter: TLS config does not work correctly.

### ISSUE THREAD

**Issue by Asya-kawai** [prometheus-community/ansible#21]
There are some issues with the TLS configuration in the README (https://github.com/prometheus-community/ansible/tree/main/roles/node_exporter#tls-config).

1. The `Create node_exporter cert dir` task defines the directory owner and group, but we should use the default values ​​defined in the node_exporter role.
2. The `Create cert and key` task uses the openssl_certificate module, but it was renamed to community.crypto.x509_certificate when moved to the collection community.crypto.
  2.1 See https://docs.ansible.com/ansible/latest/collections/community/crypto/x509_certificate_module.html
3. Before run the `Create cert and key` task, we have to create the cert_file(ex. /etc/node_exporter/tls.csr) and the key file(ex. /etc/node_exporter/tls.key) in advance, but the task that creates these files is not defined anywhere.

If give a user-friendly configuration example, change the playbook.yml as below.

```
- hosts: all
  pre_tasks:
    - name: Check if pip3 is installed
      ansible.builtin.command:
        cmd: which pip3
      register: pip3_check
      ignore_errors: true
    - name: install pip3
      ansible.builtin.apt:
        name: python3-pip
      register: pip3_install
      when:
        - pip3_check.rc is defined
        - not pip3_check.rc == 0
    - name: install cryptography python package
      ansible.builtin.pip:
        name: cryptography
      when:
        - (pip3_check.rc is defined and pip3_check.rc == 0) or (pip3_install is succeeded and pip3_install is not skipped)
    - name: Check if cryptography python package is installed
      ansible.builtin.command:
        cmd: pip3 freeze | grep cryptography
      register: cryptography_check
      ignore_errors: true
      when:
        - (pip3_check.rc is defined and pip3_check.rc == 0) or (pip3_install is succeeded and pip3_install is not skipped)
    - name: Create the node_exporter group
      ansible.builtin.group:
        name: "{{ _node_exporter_system_group }}"
        state: present
        system: true
      when: _node_exporter_system_group != "root"
    - name: Create the node_exporter user
      ansible.builtin.user:
        name: "{{ _node_exporter_system_user }}"
        groups: "{{ _node_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        create_home: false
        home: /
      when: _node_exporter_system_user != "root"
    - name: Create node_exporter cert dir
      file:
        path: "/etc/node_exporter"
        state: directory
        owner: "{{ _node_exporter_system_group }}"
        group: "{{ _node_exporter_system_group }}"
    - name: Check /etc/node_exporter exists
      stat:
        path: "/etc/node_exporter"
      register: node_exporter_dir
    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: /etc/node_exporter/tls.key
        owner: "{{ _node_exporter_system_group }}"
        group: "{{ _node_exporter_system_group }}"
      when:
        - cryptography_check is defined
        - cryptography_check.rc is defined
        - cryptography_check.rc == 0
        - node_exporter_dir.stat.exists
    - name: Create cert and key
      community.crypto.x509_certificate:
        path: /etc/node_exporter/tls.cert
        privatekey_path: /etc/node_exporter/tls.key
        provider: selfsigned
        owner: "{{ _node_exporter_system_group }}"
        group: "{{ _node_exporter_system_group }}"
      when:
        - cryptography_check is defined
        - cryptography_check.rc is defined
        - cryptography_check.rc == 0
        - node_exporter_dir.stat.exists
  roles:
    - node_exporter
  vars:
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.cert
      key_file: /etc/node_exporter/tls.key
    node_exporter_basic_auth_users:
      randomuser: examplepassword
```

Also, add conditions to the task to run the "Assert TLS configuration is correct" task as follows: This is to prevent this task from failing (e.g. if the node_exporter cert directory doesn't already exist).

```diff
+- name: Check existence of TLS cert file directory
+  ansible.builtin.stat:
+    path: "{{ node_exporter_tls_server_config.cert_file | dirname }}"
+  register: node_exporter_cert_file_dir
+  when:
+    - node_exporter_tls_server_config | length > 0
+    - node_exporter_tls_server_config.cert_file is defined
+    - node_exporter_tls_server_config.cert_file | length > 0
+
+- name: Check existence of TLS key file directory
+  ansible.builtin.stat:
+    path: "{{ node_exporter_tls_server_config.key_file | dirname }}"
+  register: node_exporter_key_file_dir
+  when:
+    - node_exporter_tls_server_config | length > 0
+    - node_exporter_tls_server_config.key_file is defined
+    - node_exporter_tls_server_config.key_file | length > 0
+
 - name: Assert that TLS config is correct
-  when: node_exporter_tls_server_config | length > 0
+  when:
+    - node_exporter_tls_server_config | length > 0
+    - node_exporter_cert_file_dir.stat is defined and node_exporter_cert_file_dir.stat.exists
+    - node_exporter_key_file_dir.stat is defined and node_exporter_key_file_dir.stat.exists
   block:
     - name: Assert that TLS key and cert path are set
       ansible.builtin.assert:
```

Writing this much README for TLS configuration is not user-friendly, so maybe we should fix the preflight.yml or configure.yml tasks.
