### ISSUE TITLE
Request for Support of time_intervals in Alertmanager Configuration

### ISSUE THREAD

**Issue by voidquark** [prometheus-community/ansible#235]
I'd like to request the enhancement of the Ansible role for Alertmanager to support the `time_intervals` feature in its configuration. This feature allows specifying time-based intervals for alert management, and it would be a valuable addition to the existing functionality.

Here is an example of how the `time_intervals` could be structured in YAML configuration:

```yaml
time_intervals:
  - name: office-hours
    time_intervals:
      - times:
          - start_time: "08:00"
            end_time: "17:00"
        weekdays: ['Monday:Friday']
```

The proposed enhancement is based on the Prometheus Alerting Configuration documentation, specifically detailed here: [Prometheus Alerting Configuration - time_interval](https://prometheus.io/docs/alerting/latest/configuration/#time_interval).

I recommend introducing new variables, possibly named `alertmanager_time_intervals`, and updating the Ansible template to accommodate this new configuration option.

Thank you for considering this enhancement request, and please let me know if you need any further information or assistance in implementing this feature.
