### ISSUE TITLE
postgres_exporter: Deployment fails if system user exists already but system group does not

### ISSUE THREAD

**Issue by fhoekstra** [prometheus-community/ansible#399]
postgres_exporter role fails if the Linux user exists, but the group does not.

The role should not just ensure the system user (`postgres_exporter_system_user`)  exists, but also that the group (`postgres_exporter_system_group`) exists, and that the user is a member.

I worked around it by adding this task to my own playbook.
```
- name: Ensure postgres exporter group exists
  ansible.builtin.group:
    name: "{{ postgres_exporter_system_group }}"
    state: present
- name: Ensure postgres exporter user exists
  ansible.builtin.user:
    name: "{{ postgres_exporter_system_user }}"
    shell: /bin/bash
    groups: "{{ postgres_exporter_system_group }}"
    append: yes
```

I'll probably make a PR for this later but just wanted to write it down so it doesn't get lost.
