### ISSUE TITLE
Tag v0.20.2 is wrongly marked as Ansible `version: 0.21.0`

### ISSUE THREAD

**Issue by andygrunwald** [prometheus-community/ansible#435]
## Context

The release https://github.com/prometheus-community/ansible/releases/tag/0.20.2 is marked as https://github.com/prometheus-community/ansible/blob/f3514a9e97dfc3d64f02aefd299487efd99e779f/galaxy.yml#L4

This is also visible on Ansible Galaxy: https://galaxy.ansible.com/ui/repo/published/prometheus/prometheus/

<img width="732" alt="Screenshot 2024-10-19 at 09 52 31" src="https://github.com/user-attachments/assets/b7db8a4e-4a1c-43be-95ef-9f8e4040a295">

If you add this version to `requirements.yml`:
```yaml
collections:
  # https://github.com/prometheus-community/ansible
  - name: prometheus.prometheus
    version: 0.20.2
```

The following error will appear:

```
ANSIBLE_CONFIG="ansible/ansible.cfg" ansible-galaxy collection install -r ansible/requirements.yml --force
Starting galaxy collection install process
Process install dependency map
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* prometheus.prometheus:0.20.2 (direct request)
Hint: Pre-releases hosted on Galaxy or Automation Hub are not installed by default unless a specific version is requested. To enable pre-releases globally, use --pre.
```

## Possible solutions

1. Create a new release with v0.21.0 (and mark the v0.20.2 in GitHub actions as faulty)
2. Create a new release with v0.20.3 (and mark the v0.20.2 in GitHub actions as faulty)

I would love to create a PR for this, but this seem to be rather Release related, which may not possible to solve via a PR.

## Workaround

Add the following to `requirements.yml`:
```yaml
collections:
  # https://github.com/prometheus-community/ansible
  - name: prometheus.prometheus
    version: 0.21.0
```
