### ISSUE TITLE
Issue: Enabling --enable-feature=auto-reload-config and --web.enable-remote-write-receiver for Prometheus 3.0

### ISSUE THREAD

**Issue by msavdert** [prometheus-community/ansible#476]
Hello,

I am trying to use the latest features introduced in Prometheus 3.0. Specifically, I want to enable the --enable-feature=auto-reload-config feature and the --web.enable-remote-write-receiver parameter for accept remote write from Grafana Alloy agent. However, I am encountering difficulties in properly configuring these parameters in playbooks.

Thanks.

**Comment by M4jx** [comment]
I'm currently facing the same issue. It is not possible to set `web.enable-remote-write-receiver` via `prometheus_config_flags_extra`

Here is a snippet from my ansible playbook

```
  roles:
    - role: prometheus.prometheus.prometheus
      prometheus_version: "3.0.0"
      prometheus_web_listen_address: "0.0.0.0:9090"
      prometheus_config_flags_extra:
        { alertmanager.timeout: 4410s, web.enable-remote-write-receiver: true }
```

Executing `sudo systemctl status prometheus.service` yields the following.
```
 prometheus.service - Prometheus
     Loaded: loaded (/etc/systemd/system/prometheus.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-11-25 16:09:17 UTC; 14min ago
   Main PID: 4517 (prometheus)
      Tasks: 8 (limit: 9478)
     Memory: 26.3M
        CPU: 1.672s
     CGroup: /system.slice/prometheus.service
             └─4517 /usr/local/bin/prometheus --storage.tsdb.path=/var/lib/prometheus --storage.tsdb.retention.time=30d --storage.tsdb.retention.size=0 --web.config.file=/etc/prometheus/web_config.yml --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --web.listen-address=0.0.0.0:9090 --web.external-url= --alertmanager.timeout=4410s  --config.file=/etc/prometheus/prometheus.yml

```

As you can see `alertmanager.timeout` was set succcessfully, but not `web.enable-remote-write-receiver`.

Tested on:
v3.0.0 and v2.54.1

**Comment by ollie-nye** [comment]
We managed to get this to behave by quoting both the key and the value in the config:

```
roles:
    - role: prometheus.prometheus.prometheus
      prometheus_version: "3.0.0"
      prometheus_web_listen_address: "0.0.0.0:9090"
      prometheus_config_flags_extra:
        alertmanager.timeout: 4410s
        "web.enable-remote-write-receiver": "true"
```

Then it seemed to behave! Not sure if the key is necessary to quote but yaml `true` is different to the string `'true'` and quoting it seems to have done the trick
