### ISSUE TITLE
How to run Node-exporter as a process instead of a system deamon?

### ISSUE THREAD

**Issue by brido4125** [prometheus-community/ansible#550]
I'm looking for a way to have the Node-exporter run as a process rather than a system deamon.

Here's what I came up with. (Note that this is not a perfect implementation)
```yaml
--- node_exporter/defaults/main.yaml
# ...

# system service or prcoess
node_exporter_run_mode: "daemon"
```

```yaml
--- node_exporter/tasks/main.yaml
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
  tags:
    - node_exporter_install
    - node_exporter_configure
    - node_exporter_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
  vars:
    _common_local_cache_path: "{{ node_exporter_local_cache_path }}"
    _common_binaries: "{{ _node_exporter_binaries }}"
    _common_binary_install_dir: "{{ node_exporter_binary_install_dir }}"
    _common_binary_url: "{{ node_exporter_binary_url }}"
    _common_checksums_url: "{{ node_exporter_checksums_url }}"
    _common_system_group: "{{ node_exporter_system_group }}"
    _common_system_user: "{{ node_exporter_system_user }}"
    _common_config_dir: "{{ node_exporter_config_dir }}"
    _common_binary_unarchive_opts: ['--strip-components=1']
  tags:
    - node_exporter_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
  vars:
    _common_selinux_port: "{{ node_exporter_web_listen_address | urlsplit('port') }}"
  when: ansible_facts['selinux'].status == "enabled"
  tags:
    - node_exporter_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - node_exporter_configure

- name: Set up run script for process mode
  ansible.builtin.include_tasks:
    file: process_setup.yml
  when: node_exporter_run_mode == "process"
  tags:
    - node_exporter_configure
    - node_exporter_run

- name: Start Node Exporter as daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
    - node_exporter_run_mode == "daemon"
  tags:
    - node_exporter_run

- name: Start Node Exporter as process
  become: true
  ansible.builtin.include_tasks:
    file: process_start.yml
  when:
    - not ansible_check_mode
    - node_exporter_run_mode == "process"
  tags:
    - node_exporter_run
```

However, this seems like a plan with a lot of change points.
so I'm wondering if there's a simpler way to do it.
