### ISSUE TITLE
Permission required for task in node_exporter role

### ISSUE THREAD

**Issue by manuel-hiller-ebm** [prometheus-community/ansible#82]
The task **Install package fact dependencies** inside the task-file **preflight.yml** inside the **node_exporter** role needs to be run a root. I noticed that while installing the node-exporter on my ubuntu server. 

The task should be changed from:
https://github.com/prometheus-community/ansible/blob/3bc2c9452fa4b42574a7baaeb9bc9796f3df805e/roles/node_exporter/tasks/preflight.yml#L7-L16

to:
```yaml
- name: Install package fact dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _pkg_fact_req }}"
    state: present
  when: (_pkg_fact_req)
  vars:
    _pkg_fact_req: "{% if (ansible_pkg_mgr == 'apt') %}\
                    {{ ('python-apt' if ansible_python_version is version('3', '<') else 'python3-apt') }}
                    {% else %}\
                    {% endif %}"
```

As a workaround you could include the role with root privileges:

```yaml
- name: Install node-exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
    apply:
      become: true
```

Thank you!
